### ISSUE TITLE
Does it work with other underlying primitive values other than long ?

### ISSUE THREAD

**Issue by rm-hull** [WellFactored/play-bindings#8]
e.g. Strings, ints or booleans

**Comment by DougC** [comment]
Yes. The wrapped value can be any type, as long as the appropriate Play typeclasses (e.g. Format, URLBinding, etc) exist for it.

**Comment by rm-hull** [comment]
Ok, great stuff; I tried it with string but didn't see the json structure I was expecting - will have another look and get back to you if i can't figure it out.

Cheers,
Rich
